-- ====================================================================
-- DATOS INICIALES - ALMACÉN (VACÍO)
-- ====================================================================
-- El almacén inicia sin productos. Agrégalos desde la interfaz web.
